@binaryStar = """
                                                                     
                                                                     
                                                                     
                                             
New Window | Help | Customize Page
							
	
STAR On-Line

		
Return to Request STAR On-Line
	
Binary Guy
	
 
PREPARED: 02/06/13 - 10:27
Guy,Binary
PROGRAM CODE: 222234006                      CATALOG YEAR: 2011
CAMPUS ID : xxxxxxx
BACHELOR OF SCIENCE DEGREE - COLLEGE OF LETTERS AND SCIENCE
COMPUTER SC & SOFTWARE ENGINEERING (COMPUTER INFO SYS) MAJOR
=================================================================
UNIVERSITY OF WISCONSIN OSHKOSH   STUDENT ACADEMIC REPORT (STAR)
REPORT NO.
 
You can register on Titan Web for
Fall 2013   as of Feb-27-2013 at 08:00 AM
 
ADVISOR: Naps,Thomas L             UGLS  J34006222
 
STUDENT ACADEMIC PROGRAM
PROGRAM : UGLS                                       2011
PLAN    : J34006222   Comp Sci(CIS)-BS               2011
 
TRANSFER INST : Northeast Wisconsin Technical    4585   JC
 
UW-OSHKOSH PLACEMENT AT TIME OF ADMISSION
ENGLISH :    Gen Ed English Comp or English 110
MATH    :    Deficient-Math 103
 
ACADEMIC STANDING : GOOD
 
COMMENTS :
 
OFFICIAL   GRADE            EARNED
GPA CREDS   POINTS    GPA    CREDS
TRANSFER INST                                0.00
UWO OFFICIAL      46.00   155.00   3.370    46.00
=================================================================
------> AT LEAST ONE REQUIREMENT HAS NOT BEEN SATISFIED <------
=================================================================
COMBINED GPA                                      (IPLIST)
UWO AND TRANSFER COURSE COMBINED GPA
(Amnesty courses excluded)
46.00 CRS EARNED
46.00 ATTEMPTED HOURS    155.00 POINTS  3.369 GPA
IN-PROG   17.00 CREDITS
 
=======================================================
IN-PROGRESS COURSES
1232 34-251  3.00      .00 IP Architecture & Assembly Lang
1232 34-262  4.00      .00 IP OO Design & Programming II
1232 38-214  3.00      .00 IP American Lit II (HU)
1232 67-171  4.00      .00 IP Calculus I (MA)
1232 73-102  3.00      .00 IP Theory Music Gen Student (HU)
 
*     =======================================================
ADJUSTMENTS TO THE COURSE REGISTRATIONS LISTED ABOVE OR
COURSES NOT COMPLETED SUCCESSFULLY WILL CHANGE THE
STATUS OF THIS REPORT.  COURSES CURRENTLY BEING
REPEATED WILL NOT BE LISTED WITH THE IN-PROGRESS COURSE
BUT WILL BE LISTED IN THE REQUIREMENT TO WHICH THEY
APPLY.
 
=======================================================
BRING YOUR STAR WITH YOU WHEN MEETING WITH YOUR ADVISOR
=================================================================
NO     GENERAL EDUCATION COMPOSITION (GCOMP)  2011-99
MINIMUM 2.00 GPA REQUIRED IN ALL APPLICABLE COURSES
TWO COURSES (6 CREDITS) REQUIRED
EARNED                                            3.330 GPA
 
+  1) COMPLETE A WRITING-BASED COMPOSITION COURSE:
1122 88-188  3.00 B+  9.99    Wrtng-Bsd Inq Sem (WBIS) (EN)
 
-  2) COMPLETE A SECOND COMPOSITION COURSE:
(MINIMUM OF 45 CREDITS REQUIRED TO ENROLL)
SELECT FROM: 38-203  38-302  38-307  38-309  38-310
38-316  38-317  38-318  38-321  38-389
=================================================================
OK     MATHEMATICS REQUIREMENT FOR THE L&S  (GMATH2BS)
BACHELOR OF SCIENCE DEGREE
 
+  1) YOU MUST COMPLETE REMEDIAL MATH COURSE 103
AND EARN A GRADE OF C OR BETTER.
1121 67-103  3.00 B+  9.99    Intermediate Algebra
 
+  2) LEVEL I COMPLETED
**NOTE: APPROPRIATE LEVEL I COURSE OPTIONS ARE BASED
ON THE STUDENT'S TEST SCORE AND THE REQUIREMENTS
FOR YOUR MAJOR. SEE AN ADVISOR FOR CORRECT SEQUENCE**
1122 67-104  3.00 C   6.00    College Algebra
 
+  3) LEVEL II MATH
4.000 GPA
1231 34-221  3.00 A  12.00    OO Design & Programming I
1232 34-262  4.00      .00 IP OO Design & Programming II
1232 67-171  4.00      .00 IP Calculus I (MA)
 
+  4) LEVEL I MATH EXEMPTED/COMPLETED WITH LEVEL II
1231 34-221  3.00 A  12.00    OO Design & Programming I
1232 67-171  4.00      .00 IP Calculus I (MA)
=================================================================
OK     GENERAL EDUCATION PHYSICAL EDUCATION (GPED)
ONE COURSE (TWO CREDITS) REQUIRED  (2011-99)
 
1121 79-105  2.00 A   8.00    Active Lifestyle (PE)
=================================================================
OK     GENERAL EDUCATION NON-WESTERN CULTURE (GNWST)
ONE COURSE (THREE CREDITS) REQUIRED
 
1122 84-101  3.00 B+  9.99    Intro to Cmpartv Pltcs(SS)(NW
=================================================================
OK     COMMUNICATION REQUIREMENT FOR THE L&S  (GSPCH2BSA)
BACHELOR OF SCIENCE AND BACHELOR OF ARTS DEGREES
 
1231 96-111  3.00 A- 11.01    Fund Spch Comm (GE)
=================================================================
OK     HUMANITIES REQUIREMENT FOR THE L&S  (GHUM2BS)
BACHELOR OF SCIENCE DEGREE
EARNED   7.00 CREDITS             4 SUB-REQS
IN-PROGRESS  6.00 CREDITS
 
1232 38-214  3.00      .00 IP American Lit II (HU)
 
1232 73-102  3.00      .00 IP Theory Music Gen Student (HU)
 
1122 76-110  3.00 B   9.00    H: Intro Philosophy (HU)
 
1122 41-110  4.00 A- 14.68    Intro French I (HU)
=================================================================
COMPLETION OF THE B.S. LAB SCIENCE AREA REQUIRES FOUR (4) COURSES
AS DESCRIBED BELOW IN AREAS 1-3.  SELECT FROM LAB SCIENCES IN
BIOLOGY, CHEMISTRY, GEOGRAPHY, GEOLOGY, PHYSICS/ASTRONOMY (NEW1)
------------  AREA #1  ------------------------------------------
TWO LABORATORY SCIENCE COURSES FROM THE SAME DEPARTMENT, ONE OF
WHICH REQUIRES THE SECOND AS A PREREQUISITE.
------------  AREA #2  ------------------------------------------
ONE NATURAL SCIENCE LABORATORY COURSE FROM A DIFFERENT DEPARTMENT
THAN THE DEPARTMENT SELECTED IN AREA #1
------------  AREA #3  ------------------------------------------
ONE COURSE THAT MATCHES ONE OF THE OPTIONS BELOW:
A)  A COURSE FROM THE SAME DEPARTMENT AS THE ONE SELECTED FOR
AREA #2 AND WHICH HAS THAT COURSE AS A PREREQUISITE
B)  A LAB SCIENCE COURSE FROM A 3RD DEPARTMENT
C)  A COURSE FROM THOSE LISTED UNDER THE B.S. MATH REQUIREMENT
=================================================================
NO     TWO PAIRS (ONE PAIR FROM EACH OF TWO DEPARTMENTS) (NEW3)
-  1) GEOLOGY DEPARTMENTAL APPROVED PAIRINGS
1231 51-102  4.00 B+ 13.32    Physical Geology (NS)
=================================================================
COMPLETE TWO COURSES FROM THE SAME NATURAL
SCIENCE DEPARTMENT.  (THE FIRST COURSE MUST
BE THE PREREQUISITE OF THE SECOND COURSE)
NOTE:  PLEASE SEE THE LIST OF APPROVED PAIRS
LOCATED IN THE PREVIOUS REQUIREMENT.
---------------------------------------------
NO OR  ONE PAIR PLUS 2 OTHER DEPARTMENTS OPTION (NEW2)
-  1) BIOLOGY DEPARTMENT APPROVED PAIRINGS
SELECT 26-105 PLUS ONE OF THE FOLLOWING:
- OR) SELECT 26-108 PLUS ONE OF THE FOLLOWING:
- OR) CHEMISTRY DEPARTMENTAL APPROVED PAIRINGS
- OR) GEOGRAPHY DEPARTMENTAL APPROVED PAIR
- OR) GEOLOGY DEPARTMENTAL APPROVED PAIRINGS
1231 51-102  4.00 B+ 13.32    Physical Geology (NS)
- OR) PHYSICS/ASTRONOMY APPROVED PAIRINGS
-  2) CHEMISTRY
-  3) -----------------------------------------------
COMPLETE A LAB SCIENCE COURSE FROM EACH OF TWO
SCIENCE DEPARTMENTS OTHER THAN THE DEPARTMENT
SELECTED FOR THE REQUIRED LAB PAIR.
......THE COURSES USED TO SATISFY THE PAIR ABOVE
WILL ALSO PRINT IN THE APPROPRIATE AREA
BELOW, BUT WILL NOT SATISFY THE DEPARTMENTAL
REQUIREMENT (A TOTAL OF THREE DEPARTMENTS
REQUIRED -- INCLUDING THE PAIR)
BIOLOGY
-  4) GEOGRAPHY
+  5) GEOLOGY
1231 51-102  4.00 B+ 13.32    Physical Geology (NS)
+  6) PHYSICS/ASTRONOMY
1121 80-101  4.00 A  16.00    Workshop Physical Science (NS
-  7) ANTHROPOLOGY
+  8) YOU MAY TAKE A SECOND MATH/STATS/COMPUTER SC.
AREA (AS DESCRIBED IN THE MATH REQUIREMENT
FOR YOUR THIRD DEPARTMENT REQUIREMENT.
1232 34-262  4.00      .00 IP OO Design & Programming II
1232 67-171  4.00      .00 IP Calculus I (MA)
=================================================================
OK     SOCIAL SCIENCE REQUIREMENT FOR THE L&S  (GSOSC2BSA)
BACHELOR OF SCIENCE AND BACHELOR OF ARTS DEGREES
EARNED  12.00 CREDITS
 
+R 1) YOU MUST COMPLETE A MINIMUM OF THREE CREDITS
OF HISTORY
3.00 CRS EARNED
1121 57-101  3.00 A- 11.01    Early Civilization (SS)
+  3) ANTHROPOLOGY (ANY COURSE EXCEPT 21-202)
3.00 CRS EARNED
1231 21-123  3.00 A- 11.01    American Ethnography (ES) (SS
+ 10) POLITICAL SCIENCE/PUBLIC ADMIN (ANY COURSE)
3.00 CRS EARNED
1122 84-101  3.00 B+  9.99    Intro to Cmpartv Pltcs(SS)(NW
+ 11) PSYCHOLOGY (ANY COURSE EXCEPT PSYCH 203, 303, 305, 310,
341,367,371,380,383,384,391,411,455,481,498 & 499)
3.00 CRS EARNED
1121 86-104  3.00 B   9.00    H: General Psychology (SS)
=================================================================
OK     GENERAL EDUCATION ETHNIC STUDIES (GETHNIC)
ONE COURSE (THREE CREDITS) REQUIRED
(IF SELECTED, 74-215 MUST BE COMPLETED FOR 3 CREDITS)
 
1231 21-123  3.00 A- 11.01    American Ethnography (ES) (SS
=================================================================
OPTIONAL GENERAL EDUCATION COURSES (NOT REQUIRED, BUT MAY
BE APPLIED TOWARD 42 CREDIT MINIMUM IN GENERAL EDUCATION)
(GOPT) (SEE E-BULLETIN OR E-TIMETABLE FOR LIST)
=================================================================
OK     GENERAL EDUCATION SUMMARY (GENEDSUM)
A MINIMUM OF 42 CREDITS IN GENERAL EDUCATION IS REQUIRED.
PLEASE REFER TO THE E-BULLETIN OR E-TIMETABLE FOR THE
APPROVED GENERAL EDUCATION LIST.
EARNED  35.00 CREDITS
35.00 ATTEMPTED HOURS    123.01 POINTS    3.514 GPA
IN-PROGRESS 10.00 CREDITS
=================================================================
NO     COMPUTER SCIENCE MAJOR (COMPUTER INFO SYSTEMS)
59 CREDITS AND A 2.00 MIN G.P.A. REQUIRED (J34006/09-9999)
EARNED   3.00 CREDITS                             4.000 GPA
IN-PROGRESS 11.00 CREDITS
--> NEEDS:  45.00 CREDITS             4 SUB-REQS      2.000 GPA
 
-  1) COMPLETE THE FOLLOWING CORE COURSES:
3.00 CRS EARNED                        4.000 GPA
IN-PROG    7.00 CREDITS
1231 34-221  3.00 A  12.00    OO Design & Programming I
1232 34-251  3.00      .00 IP Architecture & Assembly Lang
1232 34-262  4.00      .00 IP OO Design & Programming II
NEEDS:                 5 COURSES
SELECT FROM: 34-271  34-331  34-399 OR 34-490  67-212
82-311
 
-  2) COMPLETE THE FOLLOWING COURSES IN ADDITION
TO THE COMPUTER SCIENCE CORE COURSES:
.00 CRS EARNED
IN-PROG    4.00 CREDITS
1232 67-171  4.00      .00 IP Calculus I (MA)
NEEDS:                 5 COURSES
SELECT FROM: 34-341  34-346  34-350  34-361  67-201 OR
67-301 OR 36-210
 
-  3) COMPLETE A MINIMUM OF NINE CREDITS FROM THE
FOLLOWING LIST A ELECTIVE COURSES:
NEEDS:   9.00 CREDITS
SELECT FROM: 34-300  34-310  34-321  34-342  34-371
34-381  34-391  34-421  34-431  34-480
 
-  4) SELECT A MINIMUM OF 6 CREDITS FROM THE
FOLLOWING LIST B ELECTIVE COURSES:
NEEDS:   6.00 CREDITS
SELECT FROM: 28-260  28-314  28-315  28-319  28-355
28-410
 
+  5) A MINIMUM GRADE POINT AVERAGE OF 2.00 IN ALL COURSES
NUMBERED 300 OR ABOVE (EXCEPT 34-399, 34-446, 34-456,
34-474, AND 34-490) IS REQUIRED.
NEEDS:                              2.000 GPA
-> NOT FROM: 34-334  34-335  34-399  34-446  34-456
34-474  34-490
SELECT FROM: 34-300 TO 34-499
=================================================================
ELECTIVE CREDITS WHICH APPLY TO THE UNDERGRADUATE DEGREE
(ELECTIVE)
1231 51-102  4.00 B+ 13.32    Physical Geology (NS)
1122 67-104  3.00 C   6.00    College Algebra
1231 67-106  2.00 C   4.00    Trigonometry
1121 80-101  4.00 A  16.00    Workshop Physical Science (NS
=================================================================
CHECK LIMITS FOR MUSIC, DRAMA, PHY-ED PARTICIPATION
AND PROFESSIONAL COURSES (PRESUM2)
1) ONLY 4 CREDITS OF MUSIC PARTICIPATION COURSES
MAY BE APPLIED TO DEGREE CREDIT FOR NON-MUSIC MAJORS
OR MINORS.
2) ONLY 4 CREDITS OF DRAMA OR THEATRE PARTICIPATION
COURSES MAY APPLY TO DEGREE CREDITS
3) ONLY 4 CREDITS OF PHYSICAL EDUCATION ACTIVITY
COURSES MAY APPLY TO THE DEGREE CREDITS IN THIS AREA.
(ANY CREDITS OVER 4 WILL BE COUNTED AS PREPROFESSIONAL)
1121 79-105  2.00 A   8.00    Active Lifestyle (PE)
4) A MAXIMUM OF 24 PREPROFESSIONAL CREDITS MAY COUNT
TOWARD THE 120 REQUIRED TO GRADUATE.
=================================================================
NO     GENERAL BACCALAUREATE DEGREE REQUIREMENTS  (SUMMARY)
 
-  1) EARN A MINIMUM OF 120 DEGREE CREDITS
43.00 CRS EARNED
IN-PROG   17.00 CREDITS
NEEDS:  60.00 CREDITS
 
+  3) EARN A MINIMUM 2.00 GPA IN UWO CREDITS ATTEMPTED
46.00 ATTEMPTED HOURS    155.00 POINTS  3.369 GPA
 
+  4) EARN A MINIMUM 2.00 GPA IN ALL COURSES APPLICABLE TO
THE UNIVERSITY'S GENERAL EDUCATION ENGLISH COMPOSITION
REQUIREMENT
3.330 GPA
 
+  5) EARN AT LEAST 30 SEMESTER CREDITS AT UW OSHKOSH
( 46.00 CREDITS TAKEN)
IN-PROG   17.00 CREDITS
 
+  6) EARN AT LEAST 48 CREDITS FROM A 4 YEAR INSTITUTION
( 46.00 CREDITS TAKEN)
IN-PROG   17.00 CREDITS
 
-  7) EARN AT LEAST 35 CREDITS AT THE UPPER LEVEL (300/400)
WITH A MINIMUM 2.00 GPA
NEEDS:  35.00 CREDITS
 
+  8) 15 OF THE LAST 30 CREDITS MUST BE TAKEN AT UWO.
( 15.00 CREDITS TAKEN)
IN-PROG   17.00 CREDITS
=================================================================
CREDITS NOT APPLICABLE TO THE UNDERGRADUATE DEGREE
(REMEDIAL & GRADUATE COURSES)
 
-     REMEDIAL COURSES NOT APPLIED TO UNDERGRAD DEGREE
1121 67-103  3.00 B+  9.99    Intermediate Algebra
=================================================================
**** LEGEND ****
NO = REQUIREMENT NOT COMPLETE     >D = DUPLICATE COURSE - CREDIT
OK = REQUIREMENT COMPLETE              & GPA EFFECT REMOVED ON
- = SUBREQUIREMENT NOT COMPLETE       COURSE EXCEEDING LIMIT
+ = SUBREQUIREMENT COMPLETE      >X = REPEATED COURSE - CREDIT
* = SUBREQUIREMENT IS OPTIONAL        & GPA EFFECT REMOVED ON
(R)= REQUIRED COURSE                   ORIGINAL COURSE
+R = REQUIRED SUBREQUIREMENT      >S = COURSE CREDIT SPLIT
COMPLETED                         BETWEEN REQUIREMENTS
-R = REQUIRED SUBREQUIREMENT      >R = REPEATABLE COURSE - CREDIT
NOT COMPLETED                     MAY BE EARNED MORE THAN
CS = COURSE SUBSTITUTION               ONCE
WC = WAIVED COURSE                WH = WAIVED CREDIT HOUR
<> = CONTINUED REQUIREMENT        >C = DUPLICAT CROSS-LINKED COUR
S = SATISFACTORY GRADE IN RETRO., MILITARY, DEPT., TEST OUT CR.
******
PLEASE NOTE: THE FOUR NUMBERS BEFORE A COURSE INDICATE THE TERM
IN WHICH THE COURSE WAS TAKEN.  THE FIRST THREE NUMBERS INDICATE
THE ACADEMIC YEAR (078 IS USED FOR THE 2007-08 ACADEMIC YEAR).
THE LAST NUMBER INDICATES THE TERM (1 = FALL, 2 = SPRING,
4 = SUMMER).  FOR EXAMPLE, 0782 IS THE SPRING TERM OF 2007-08.
****************************************************************
******
THIS NOTICE OF ACADEMIC PROGRESS HAS BEEN PREPARED TO ASSIST YOU
DURING YOUR COLLEGE EXPERIENCE.  ALTHOUGH EFFORTS HAVE BEEN MADE
TO ASSESS THE ACCURACY OF THIS REPORT, YOU ARE RESPONSIBLE FOR
MAKING SURE THAT ALL REQUIREMENTS HAVE BEEN COMPLETED.  THE
REGISTRAR'S OFFICE WILL ULTIMATELY AUTHORIZE THE AWARDING OF
YOUR DEGREE; THEREFORE, IF YOU HAVE ANY QUESTIONS ABOUT THE
ACCURACY OF THIS PROGRESS REPORT, PLEASE SEE AN ACADEMIC ADVISOR
IN DEMPSEY 130.
*******
****************************************************************
=================================================================
THIS AUDIT ASSUMES SUCCESSFUL COMPLETION OF ALL IN-PROGRESS
COURSES; ANY IN-PROGRESS COURSES NOT COMPLETED SUCCESSFULLY
MAY CHANGE THIS AUDIT'S EVALUATION.
-----------------------------------------------------------------
****    CONFIDENTIAL -  STUDENT/ADVISOR USE ONLY         ****
****  FEDERAL LAW PROHIBITS TRANSMITTAL TO A THIRD PARTY ****
-----------------------------------------------------------------
DEPARTMENT CONVERSION TABLE
HONORS                    00       HEALTH                    55
SERVICE COURSES IN EDUC   11       HEALTH EDUCATION          55
EDUCATIONAL FOUNDATIONS   12       CHINESE                   56
ELEMENTARY EDUCATION      13       HISTORY                   57
SECONDARY EDUCATION       14       INTERNATIONAL STUDIES     59
READING EDUCATION         15       JOURNALISM                61
SPECIAL EDUCATION         16       KINESIOLOGY               77
EDUCATIONAL LEADERSHIP    17       MATHEMATICS               67
HUMAN SERVICES            18       MEDICAL TECHNOLOGY        68
ANTHROPOLOGY              21       MILITARY SCIENCE          70
ART                       22       NURSING COLLABORATIVE     71
AFRICAN AMERICAN STUDIES  23       MUSIC                     73
BIOLOGY                   26       NURSING                   74
BUSINESS                  28       PHILOSOPHY                76
COUNSELOR EDUCATION       29       PHYSICAL EDUCATION        79
PROFESSIONAL COUNSELING   29       PHYSICAL SCIENCE          80
LIBERAL STUDIES           31       PUBLIC ADMINISTRATION     81
CHEMISTRY                 32       PHYSICS/ASTRONOMY         82
COMPUTER SCIENCE          34       POLITICAL SCIENCE         84
CRIMINAL JUSTICE          35       PRACTICAL ARTS            85
ECONOMICS                 36       PSYCHOLOGY                86
ENVIRONMENTAL STUDIES     37       RELIGIOUS STUDIES         87
ENGLISH                   38       WRITING-BASED INQ SEM     88
FRENCH                    41       PROBLEM-BASED INQ SEM     89
GERMAN                    43       SOCIAL JUSTICE            91
JAPANESE                  44       SOCIOLOGY                 92
RUSSIAN                   48       SOCIAL WORK               93
SPANISH                   49       INTERDISCIPLINARY STDS    94
GEOGRAPHY                 50       COMMUNICATION             96
GEOLOGY                   51       THEATRE                   97
ARAPAHO                   53       WOMEN'S STUDIES           98
SHOSHONE                  54       URBAN PLANNING            99
-----------------------------------------------------------------
=================================================================
********************* END OF ANALYSIS *********************


	
Return to Academics
""";